/* capturer.c
 *
 * Requires: libcurl
 *
 * Default snapshot URL:
 *   http://127.0.0.1:8008/?action=snapshot
 *
 * Source code generated by ChatGPT 5
 */
// final_path variable has double / in the path. Linux allows for it. Should we correcti it?
// The file is saved as tmp and then renamed. Why?

#include <curl/curl.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <libgen.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>

#include "log_msgs.h"
#include "capturer.h"

#define CAPTURER_SNAPSHOT_URL "http://127.0.0.1:8008/?action=snapshot"

static char g_capture_path[PATH_MAX + 1];
static char g_snapshot_url[1024];
static int g_initialized = 0;
static int g_curl_global_initialized = 0;

static int make_directory_recursive(const char *path)
  {
   char tmp[PATH_MAX + 1];
   size_t i;
   struct stat st;

   if(path == NULL || strlen(path) == 0 || strlen(path) > PATH_MAX)
      return(EINVAL);

   if(strlen(path) >= sizeof(tmp))
      return(ENAMETOOLONG);

   strcpy(tmp, path);

   for(i = 1; tmp[i] != '\0'; i++)
     {
      if(tmp[i] == '/')
        {
         tmp[i] = '\0';
         if(strlen(tmp) > 0)
           {
            if(stat(tmp, &st) != 0)
              {
               if(mkdir(tmp, 0755) != 0 && errno != EEXIST)
                  return(errno);
              }
            else if(!S_ISDIR(st.st_mode))
               return(ENOTDIR);
           }
         tmp[i] = '/';
        }
     }

   if(stat(tmp, &st) != 0)
     {
      if(mkdir(tmp, 0755) != 0 && errno != EEXIST)
         return(errno);
     }
   else if(!S_ISDIR(st.st_mode))
      return(ENOTDIR);

   return(0);
  }

static int validate_filename(const char *filename_to_save)
  {
   if(filename_to_save == NULL)
      return(EINVAL);

   if(strlen(filename_to_save) == 0 || strlen(filename_to_save) > PATH_MAX)
      return(EINVAL);

   if(strchr(filename_to_save, '/') != NULL)
      return(EINVAL);

   if(strstr(filename_to_save, "..") != NULL)
      return(EINVAL);

   return(0);
  }

static int build_full_path(char *dst, size_t dst_size, const char *dir, const char *file)
  {
   int ret;

   if(dst == NULL || dir == NULL || file == NULL)
      return(EINVAL);

   ret = snprintf(dst, dst_size, "%s/%s", dir, file);
   if(ret < 0)
      return(EIO);

   if((size_t)ret >= dst_size)
      return(ENAMETOOLONG);

   return(0);
  }

static size_t curl_write_cb(void *ptr, size_t size, size_t nmemb, void *userdata)
  {
   FILE *fp;
   size_t written;
   size_t total;

   fp = (FILE *)userdata;
   total = size * nmemb;

   if(fp == NULL || ptr == NULL || total == 0)
      return(0);

   written = fwrite(ptr, size, nmemb, fp);
   if(written != nmemb)
      return(0);

   return(total);
  }

static int curl_result_to_errno(CURLcode code)
  {
   switch(code)
     {
      case CURLE_OK:
         return(0);

      case CURLE_OUT_OF_MEMORY:
         return(ENOMEM);

      case CURLE_COULDNT_CONNECT:
         return(ECONNREFUSED);

      case CURLE_OPERATION_TIMEDOUT:
         return(ETIMEDOUT);

      case CURLE_URL_MALFORMAT:
         return(EINVAL);

      case CURLE_HTTP_RETURNED_ERROR:
         return(EIO);

      case CURLE_SEND_ERROR:
      case CURLE_RECV_ERROR:
      case CURLE_WRITE_ERROR:
      case CURLE_GOT_NOTHING:
      case CURLE_PARTIAL_FILE:
         return(EIO);

      default:
         return(EIO);
     }
  }

int capturer_init(const char *full_capture_path)
  {
   int ret_error;

   if(full_capture_path == NULL || strlen(full_capture_path) == 0 || strlen(full_capture_path) > PATH_MAX)
      {
       log_printf("Error: capturer_init received an invalid capture path.\n");
       return(EINVAL);
      }

   ret_error = make_directory_recursive(full_capture_path);
   if(ret_error != 0)
     {
      log_printf("Error: capturer cannot create or access directory %s. errno=%d\n", full_capture_path, ret_error);
      return(ret_error);
     }

   if(strlen(full_capture_path) >= sizeof(g_capture_path))
     {
      log_printf("Error: capturer capture path too long: %s\n", full_capture_path);
      return(ENAMETOOLONG);
     }

   strcpy(g_capture_path, full_capture_path);

   if(strlen(CAPTURER_SNAPSHOT_URL) >= sizeof(g_snapshot_url))
     {
      log_printf("Error: capturer default snapshot URL too long.\n");
      return(ENAMETOOLONG);
     }

   strcpy(g_snapshot_url, CAPTURER_SNAPSHOT_URL);

   if(!g_curl_global_initialized)
     {
      if(curl_global_init(CURL_GLOBAL_DEFAULT) != 0)
        {
         log_printf("Error: capturer cannot initialize libcurl global state.\n");
         return(EIO);
        }

      g_curl_global_initialized = 1;
     }

   g_initialized = 1;
   return(0);
  }

int capturer_get_frame(const char *filename_to_save)
  {
   int ret_error;
   char final_path[PATH_MAX + 1];
   char temp_path[PATH_MAX + 1];
   FILE *fp;
   CURL *curl;
   CURLcode curl_res;
   long http_code;
   struct stat st;

   if(!g_initialized)
     {
      log_printf("Error: capturer_get_frame called before capturer_init.\n");
      return(ENODEV);
     }

   ret_error = validate_filename(filename_to_save);
   if(ret_error != 0)
     {
      log_printf("Error: capturer_get_frame received an invalid filename.\n");
      return(ret_error);
     }

   ret_error = build_full_path(final_path, sizeof(final_path), g_capture_path, filename_to_save);
   if(ret_error != 0)
     {
      log_printf("Error: capturer cannot build destination path for %s. errno=%d\n", filename_to_save, ret_error);
      return(ret_error);
     }

   ret_error = build_full_path(temp_path, sizeof(temp_path), g_capture_path, filename_to_save);
   if(ret_error != 0)
     {
      log_printf("Error: capturer cannot build temporary path for %s. errno=%d\n", filename_to_save, ret_error);
      return(ret_error);
     }

   if(strlen(temp_path) + 5 >= sizeof(temp_path))
     {
      log_printf("Error: capturer temporary path too long for %s.\n", filename_to_save);
      return(ENAMETOOLONG);
     }

   strcat(temp_path, ".tmp");

   fp = fopen(temp_path, "wb");
   if(fp == NULL)
     {
      log_printf("Error: capturer cannot create the file %s for the downloaded image. errno=%d\n", temp_path, errno);
      return(errno);
     }

   curl = curl_easy_init();
   if(curl == NULL)
     {
      log_printf("Error: capturer cannot initialize curl easy handle.\n");
      fclose(fp);
      unlink(temp_path);
      return(ENOMEM);
     }

   curl_easy_setopt(curl, CURLOPT_URL, g_snapshot_url);
   curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, curl_write_cb);
   curl_easy_setopt(curl, CURLOPT_WRITEDATA, fp);
   curl_easy_setopt(curl, CURLOPT_FAILONERROR, 1L);
   curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
   curl_easy_setopt(curl, CURLOPT_NOSIGNAL, 1L);
   curl_easy_setopt(curl, CURLOPT_CONNECTTIMEOUT_MS, 5000L);
   curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, 15000L);
   curl_easy_setopt(curl, CURLOPT_USERAGENT, "capturer/1.0");

   curl_res = curl_easy_perform(curl);
   if(curl_res != CURLE_OK)
     {
      log_printf("Error: capturer cannot download frame from %s. curl=%d (%s)\n",
                 g_snapshot_url, (int)curl_res, curl_easy_strerror(curl_res));
      curl_easy_cleanup(curl);
      fclose(fp);
      unlink(temp_path);
      return(curl_result_to_errno(curl_res));
     }

   curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
   if(http_code < 200 || http_code >= 300)
     {
      log_printf("Error: capturer got HTTP code %ld from %s\n", http_code, g_snapshot_url);
      curl_easy_cleanup(curl);
      fclose(fp);
      unlink(temp_path);
      return(EIO);
     }

   if(fflush(fp) != 0)
     {
      log_printf("Error: capturer cannot flush file %s. errno=%d\n", temp_path, errno);
      curl_easy_cleanup(curl);
      fclose(fp);
      unlink(temp_path);
      return(errno);
     }

   if(fsync(fileno(fp)) != 0)
     {
      log_printf("Error: capturer cannot sync file %s. errno=%d\n", temp_path, errno);
      curl_easy_cleanup(curl);
      fclose(fp);
      unlink(temp_path);
      return(errno);
     }

   if(fclose(fp) != 0)
     {
      log_printf("Error: capturer cannot close file %s. errno=%d\n", temp_path, errno);
      curl_easy_cleanup(curl);
      unlink(temp_path);
      return(errno);
     }

   curl_easy_cleanup(curl);

   if(stat(final_path, &st) == 0)
     {
      if(unlink(final_path) != 0)
        {
         log_printf("Error: capturer cannot remove previous image file %s. errno=%d\n", final_path, errno);
         unlink(temp_path);
         return(errno);
        }
     }

   if(rename(temp_path, final_path) != 0)
     {
      log_printf("Error: capturer cannot rename %s to %s. errno=%d\n", temp_path, final_path, errno);
      unlink(temp_path);
      return(errno);
     }
   log_printf("Camera frame has been downloaded and stored in %s\n", final_path);

   return(0);
  }

void capturer_deinit(void)
  {
   if(g_curl_global_initialized)
     {
      curl_global_cleanup();
      g_curl_global_initialized = 0;
     }

   g_initialized = 0;
   g_capture_path[0] = '\0';
   g_snapshot_url[0] = '\0';
  }
