// Raspberry Pi GPIO control library using interface library libgpiod 2.x
// Source code mostly generated by ChatGPT 5

#include <errno.h>
#include <gpiod.h>
#include <stdlib.h>
#include <string.h>

#include "gpio_control.h"

#define GPIO_CONTROL_DEFAULT_CHIP_PATH "/dev/gpiochip0"
#define GPIO_CONTROL_CONSUMER_NAME "gpio_control"

typedef struct
  {
   struct gpiod_line_request *request;
   int direction;
  } gpio_pin_ctx_t;

static struct gpiod_chip *g_gpio_chip = NULL;
static gpio_pin_ctx_t *g_pin_ctxs = NULL;
static size_t g_num_lines = 0;
static int g_library_opened = 0;

static int get_errno_or_io(void)
  {
   if(errno != 0)
      return(errno);

   return(EIO);
  }

static int validate_library_opened(void)
  {
   if(g_library_opened == 0 || g_gpio_chip == NULL || g_pin_ctxs == NULL)
      return(EBADF);

   return(0);
  }

static int validate_pin(int pin)
  {
   if(pin < 0)
      return(EINVAL);

   if((size_t)pin >= g_num_lines)
      return(EINVAL);

   return(0);
  }

static void release_pin_request(gpio_pin_ctx_t *pin_ctx)
  {
   if(pin_ctx != NULL && pin_ctx->request != NULL)
     {
      gpiod_line_request_release(pin_ctx->request);
      pin_ctx->request = NULL;
     }
  }

static void release_all_pin_requests(void)
  {
   size_t i;

   if(g_pin_ctxs == NULL)
      return;

   for(i = 0; i < g_num_lines; i++)
      release_pin_request(&g_pin_ctxs[i]);
  }

static int configure_line_settings(struct gpiod_line_settings *settings, int dir, int initial_value)
  {
   int ret;

   if(settings == NULL)
      return(EINVAL);

   switch(dir)
     {
      case PIN_IN_DIR:
         ret = gpiod_line_settings_set_direction(settings, GPIOD_LINE_DIRECTION_INPUT);
         if(ret != 0)
            return(get_errno_or_io());

         ret = gpiod_line_settings_set_bias(settings, GPIOD_LINE_BIAS_DISABLED);
         if(ret != 0)
            return(get_errno_or_io());
         break;

      case PIN_IN_DIR_PULLDOWN:
         ret = gpiod_line_settings_set_direction(settings, GPIOD_LINE_DIRECTION_INPUT);
         if(ret != 0)
            return(get_errno_or_io());

         ret = gpiod_line_settings_set_bias(settings, GPIOD_LINE_BIAS_PULL_DOWN);
         if(ret != 0)
            return(get_errno_or_io());
         break;

      case PIN_IN_DIR_PULLUP:
         ret = gpiod_line_settings_set_direction(settings, GPIOD_LINE_DIRECTION_INPUT);
         if(ret != 0)
            return(get_errno_or_io());

         ret = gpiod_line_settings_set_bias(settings, GPIOD_LINE_BIAS_PULL_UP);
         if(ret != 0)
            return(get_errno_or_io());
         break;

      case PIN_OUT_DIR:
         ret = gpiod_line_settings_set_direction(settings, GPIOD_LINE_DIRECTION_OUTPUT);
         if(ret != 0)
            return(get_errno_or_io());

         ret = gpiod_line_settings_set_bias(settings, GPIOD_LINE_BIAS_DISABLED);
         if(ret != 0)
            return(get_errno_or_io());

         ret = gpiod_line_settings_set_output_value(settings,
                                                    (initial_value == PIN_HIGH_VAL) ?
                                                     GPIOD_LINE_VALUE_ACTIVE :
                                                     GPIOD_LINE_VALUE_INACTIVE);
         if(ret != 0)
            return(get_errno_or_io());
         break;

      default:
         return(EINVAL);
     }

   return(0);
  }

static int build_line_request(unsigned int pin, int dir, int initial_value, struct gpiod_line_request **request_out)
  {
   struct gpiod_line_settings *settings = NULL;
   struct gpiod_line_config *line_cfg = NULL;
   struct gpiod_request_config *req_cfg = NULL;
   struct gpiod_line_request *request = NULL;
   unsigned int offset;
   int ret = 0;

   if(request_out == NULL)
      return(EINVAL);

   *request_out = NULL;
   offset = pin;

   do
     {
      settings = gpiod_line_settings_new();
      if(settings == NULL)
        {
         ret = get_errno_or_io();
         break;
        }

      ret = configure_line_settings(settings, dir, initial_value);
      if(ret != 0)
         break;

      line_cfg = gpiod_line_config_new();
      if(line_cfg == NULL)
        {
         ret = get_errno_or_io();
         break;
        }

      ret = gpiod_line_config_add_line_settings(line_cfg, &offset, 1, settings);
      if(ret != 0)
        {
         ret = get_errno_or_io();
         break;
        }

      req_cfg = gpiod_request_config_new();
      if(req_cfg == NULL)
        {
         ret = get_errno_or_io();
         break;
        }

      gpiod_request_config_set_consumer(req_cfg, GPIO_CONTROL_CONSUMER_NAME);

      request = gpiod_chip_request_lines(g_gpio_chip, req_cfg, line_cfg);
      if(request == NULL)
        {
         ret = get_errno_or_io();
         break;
        }

      *request_out = request;
      request = NULL;
     }
   while(0);

   if(request != NULL)
      gpiod_line_request_release(request);

   if(req_cfg != NULL)
      gpiod_request_config_free(req_cfg);

   if(line_cfg != NULL)
      gpiod_line_config_free(line_cfg);

   if(settings != NULL)
      gpiod_line_settings_free(settings);

   return(ret);
  }

int open_gpios(void)
  {
   const char *chip_path;
   struct gpiod_chip_info *chip_info = NULL;
   size_t num_lines;
   gpio_pin_ctx_t *pin_ctxs;

   if(g_library_opened != 0)
      return(0);

   chip_path = getenv("GPIO_CONTROL_CHIP");
   if(chip_path == NULL || chip_path[0] == '\0')
      chip_path = GPIO_CONTROL_DEFAULT_CHIP_PATH;

   g_gpio_chip = gpiod_chip_open(chip_path);
   if(g_gpio_chip == NULL)
      return(get_errno_or_io());

   chip_info = gpiod_chip_get_info(g_gpio_chip);
   if(chip_info == NULL)
     {
      gpiod_chip_close(g_gpio_chip);
      g_gpio_chip = NULL;
      return(get_errno_or_io());
     }

   num_lines = gpiod_chip_info_get_num_lines(chip_info);
   gpiod_chip_info_free(chip_info);
   chip_info = NULL;

   if(num_lines == 0)
     {
      gpiod_chip_close(g_gpio_chip);
      g_gpio_chip = NULL;
      return(ENODEV);
     }

   pin_ctxs = calloc(num_lines, sizeof(*pin_ctxs));
   if(pin_ctxs == NULL)
     {
      gpiod_chip_close(g_gpio_chip);
      g_gpio_chip = NULL;
      return(ENOMEM);
     }

   g_pin_ctxs = pin_ctxs;
   g_num_lines = num_lines;
   g_library_opened = 1;

   return(0);
  }

int close_gpios(void)
  {
   if(g_library_opened == 0)
      return(0);

   release_all_pin_requests();

   if(g_pin_ctxs != NULL)
     {
      free(g_pin_ctxs);
      g_pin_ctxs = NULL;
     }

   g_num_lines = 0;

   if(g_gpio_chip != NULL)
     {
      gpiod_chip_close(g_gpio_chip);
      g_gpio_chip = NULL;
     }

   g_library_opened = 0;

   return(0);
  }

int gpio_direction(int pin, int dir)
  {
   gpio_pin_ctx_t *pin_ctx;
   struct gpiod_line_request *new_request = NULL;
   int ret;
   int initial_value = PIN_LOW_VAL;
   int old_direction;
   int old_value = PIN_LOW_VAL;
   enum gpiod_line_value current_value;

   ret = validate_library_opened();
   if(ret != 0)
      return(ret);

   ret = validate_pin(pin);
   if(ret != 0)
      return(ret);

   pin_ctx = &g_pin_ctxs[pin];
   old_direction = pin_ctx->direction;

   if(pin_ctx->request != NULL && old_direction == PIN_OUT_DIR)
     {
      current_value = gpiod_line_request_get_value(pin_ctx->request, (unsigned int)pin);
      if(current_value == GPIOD_LINE_VALUE_ERROR)
         return(get_errno_or_io());

      if(current_value == GPIOD_LINE_VALUE_ACTIVE)
         old_value = PIN_HIGH_VAL;
     }

   release_pin_request(pin_ctx);

   ret = build_line_request((unsigned int)pin, dir, initial_value, &new_request);
   if(ret != 0)
     {
      if(old_direction == PIN_IN_DIR || old_direction == PIN_IN_DIR_PULLDOWN ||
         old_direction == PIN_IN_DIR_PULLUP || old_direction == PIN_OUT_DIR)
        {
         if(build_line_request((unsigned int)pin, old_direction, old_value, &new_request) == 0)
           {
            pin_ctx->request = new_request;
            pin_ctx->direction = old_direction;
           }
        }

      return(ret);
     }

   pin_ctx->request = new_request;
   pin_ctx->direction = dir;

   return(0);
  }

int gpio_read(int pin, int *value)
  {
   gpio_pin_ctx_t *pin_ctx;
   enum gpiod_line_value line_value;
   int ret;

   if(value == NULL)
      return(EINVAL);

   ret = validate_library_opened();
   if(ret != 0)
      return(ret);

   ret = validate_pin(pin);
   if(ret != 0)
      return(ret);

   pin_ctx = &g_pin_ctxs[pin];
   if(pin_ctx->request == NULL)
      return(EINVAL);

   line_value = gpiod_line_request_get_value(pin_ctx->request, (unsigned int)pin);
   if(line_value == GPIOD_LINE_VALUE_ERROR)
      return(get_errno_or_io());

   if(line_value == GPIOD_LINE_VALUE_ACTIVE)
      *value = PIN_HIGH_VAL;
   else
      *value = PIN_LOW_VAL;

   return(0);
  }

int gpio_write(int pin, int value)
  {
   gpio_pin_ctx_t *pin_ctx;
   enum gpiod_line_value line_value;
   int ret;

   if(value != PIN_LOW_VAL && value != PIN_HIGH_VAL)
      return(EINVAL);

   ret = validate_library_opened();
   if(ret != 0)
      return(ret);

   ret = validate_pin(pin);
   if(ret != 0)
      return(ret);

   pin_ctx = &g_pin_ctxs[pin];
   if(pin_ctx->request == NULL)
      return(EINVAL);

   if(pin_ctx->direction != PIN_OUT_DIR)
      return(EPERM);

   line_value = (value == PIN_HIGH_VAL) ? GPIOD_LINE_VALUE_ACTIVE : GPIOD_LINE_VALUE_INACTIVE;
   ret = gpiod_line_request_set_value(pin_ctx->request, (unsigned int)pin, line_value);
   if(ret != 0)
      return(get_errno_or_io());

   return(0);
  }


int configure_gpios(void)
  {
   int ret_err;
   int curr_gpio;

   // Set GPIO direction as input
   curr_gpio=PIR_GPIO;
   ret_err=gpio_direction(curr_gpio, PIN_IN_DIR);
   if (0 == ret_err)
     {
      // Set GPIO directions as output and values
      curr_gpio=RELAY1_GPIO;
      ret_err=gpio_direction(curr_gpio, PIN_OUT_DIR);
      if (0 == ret_err)
        {
         gpio_write(curr_gpio, PIN_HIGH_VAL);
         curr_gpio=RELAY2_GPIO;
         ret_err=gpio_direction(curr_gpio, PIN_OUT_DIR);
         if (0 == ret_err)
           {
            gpio_write(curr_gpio, PIN_HIGH_VAL);
            curr_gpio=RELAY3_GPIO;
            ret_err=gpio_direction(curr_gpio, PIN_OUT_DIR);
            if (0 == ret_err)
              {
               gpio_write(curr_gpio, PIN_HIGH_VAL);
               curr_gpio=RELAY4_GPIO;
               ret_err=gpio_direction(curr_gpio, PIN_OUT_DIR);
               if (0 == ret_err)
                 {
                  gpio_write(curr_gpio, PIN_HIGH_VAL);
                  // Set GPIO directions as input pull-up
                  curr_gpio=CONTACT1_GPIO;
                  ret_err=gpio_direction(curr_gpio, PIN_IN_DIR_PULLUP);
                  if (0 == ret_err)
                    {
                     curr_gpio=CONTACT2_GPIO;
                     ret_err=gpio_direction(curr_gpio, PIN_IN_DIR_PULLUP);
                     if (0 == ret_err)
                       {
                        // Set GPIO direction as output (this pin value is used as flag)
                        curr_gpio=ARMING_GPIO;
                        ret_err=gpio_direction(curr_gpio, PIN_OUT_DIR);
                        if (0 == ret_err)
                           gpio_write(curr_gpio, PIN_HIGH_VAL);
                       }
                    }
                 }
              }
           }
        }
     }
   return(ret_err);
  }
